# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(default=False, editable=False, help_text='Is an image file', verbose_name='Is image'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Video URL'),
        ),
    ]
