# Generated by Django 2.2.12 on 2020-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200429_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Is an image file', verbose_name='Is image'),
        ),
    ]
