# Generated by Django 3.2.12 on 2022-04-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperclip', '__first__'),
        ('test_app', '0004_auto_20220405_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paperclip.license')),
                ('bar', models.CharField(max_length=100)),
            ],
            bases=('paperclip.license',),
        ),
        migrations.AddField(
            model_name='attachment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.license', verbose_name='License'),
        ),
    ]
