# Generated by Django 3.1.7 on 2023-01-30 10:51

from django.db import migrations, models
import paperclip.models
import paperclip.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20220425_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='random_suffix',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=512, upload_to=paperclip.models.attachment_upload, validators=[paperclip.validators.FileMimetypeValidator()], verbose_name='File'),
        ),
    ]
