# Generated by Django 4.0.4 on 2022-06-01 14:40

from django.db import migrations, models
import paperclip.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20220425_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=512, upload_to=paperclip.models.attachment_upload, validators=[paperclip.models.validate_image], verbose_name='File'),
        ),
    ]
